//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shing.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shing.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;        var ue_t0 = ue_t0 || +new Date();&lt;/script&gt;
        ///    &lt;script type=&apos;text/javascript&apos;&gt;
        ///        var ue_id = &apos;0GHVQH2HRCRB4503GXSG&apos;,
        ///ue_sid = &apos;179-0116821-8645332&apos;,
        ///ue_mid = &apos;ATVPDKIKX0DER&apos;,
        ///ue_url = &apos;/registry/wishlist/28B0NJ50RIV34/ref=cm_wl_sb_o/uedata/179-0116821-8645332/NoPageType&apos;,
        ///ue_furl = &apos;fls-na.amazon.com&apos;,
        ///ue_pr = 0,
        ///ue_navtiming = 1;
        ///        ue_rnt = 0;
        ///        var ueinit = (ueinit || 0) + 1; var ue = { t0: ue_t0, id: ue_id, url: ue_url [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Compact {
            get {
                return ResourceManager.GetString("Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;        var ue_t0 = ue_t0 || +new Date();&lt;/script&gt;
        ///    &lt;script type=&apos;text/javascript&apos;&gt;
        ///        var ue_id = &apos;0GHVQH2HRCRB4503GXSG&apos;,
        ///ue_sid = &apos;179-0116821-8645332&apos;,
        ///ue_mid = &apos;ATVPDKIKX0DER&apos;,
        ///ue_url = &apos;/registry/wishlist/28B0NJ50RIV34/ref=cm_wl_sb_o/uedata/179-0116821-8645332/NoPageType&apos;,
        ///ue_furl = &apos;fls-na.amazon.com&apos;,
        ///ue_pr = 0,
        ///ue_navtiming = 1;
        ///        ue_rnt = 0;
        ///        var ueinit = (ueinit || 0) + 1; var ue = { t0: ue_t0, id: ue_id, url: ue_url [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Compact_17_items {
            get {
                return ResourceManager.GetString("Compact_17_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- NO ITEMS TEST RESPONSE FROM AMAZON --&gt;
        ///
        ///
        ///
        ///
        ///
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;    var ue_t0 = ue_t0 || +new Date();&lt;/script&gt;
        ///&lt;script type=&apos;text/javascript&apos;&gt;
        ///    var ue_wl_jserr = 1;
        ///    var ue_err = { ec: 0, pec: 0, ts: 0, startTimer: function () { ue_err.ts++; setInterval(function () { window.ue &amp;&amp; (ue_err.pec &lt; ue_err.ec) &amp;&amp; uex(&quot;at&quot;); ue_err.pec = ue_err.ec }, 10000) } }; function ueLogError(a, c, b) { ue_err.ec++; ue.log({ m: a, f: c, l: b }, &quot;jserr&quot;); return false };
        ///&lt;/scrip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Compact_No_Items {
            get {
                return ResourceManager.GetString("Compact_No_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;    var ue_t0 = ue_t0 || +new Date();&lt;/script&gt;
        ///&lt;script type=&apos;text/javascript&apos;&gt;
        ///    var ue_id = &apos;0N5TX6KT034M7HWJPGHE&apos;,
        ///ue_sid = &apos;186-1571468-1782915&apos;,
        ///ue_mid = &apos;ATVPDKIKX0DER&apos;,
        ///ue_url = &apos;/gp/registry/wishlist/3ON5W8HBTKUOI/ref=wl_web/uedata/186-1571468-1782915/NoPageType&apos;,
        ///ue_furl = &apos;fls-na.amazon.com&apos;,
        ///ue_pr = 0,
        ///ue_navtiming = 1,
        ///ue_rnt = 0,
        ///ue_tm = 60000,
        ///ue_wn = 4;
        ///    var ueinit = (ueinit || 0) + 1; var ue = { t0: ue_t0, id: ue_id, url: ue_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Full_25_items {
            get {
                return ResourceManager.GetString("Full_25_items", resourceCulture);
            }
        }
    }
}
